### ISSUE TITLE
Something is wrong with attaching navigationProperties when done in different orders

### ISSUE THREAD

**Issue by bramski** [Breeze/breeze.js#17]
So I have three entity types:

```
addType
      name: 'DaySchedule'
      apiVersion: 3
      dataProperties:
        uid: "uid"
        employee_id: "int"
        day: "string"
        shifts:
          complexType: "Shift"
          hasMany: true
      navigationProperties:
        employee:
          type: "Employee"
          assoc: "DayScheduleEmployee"
          key: ["employee_id"]

addType
      name: 'Employee'
      dataProperties:
        id: "id"
        details:
          complexType: "EmployeeDetails"
      navigationProperties:
        schedules:
          entityTypeName: "DaySchedule"
          hasMany: true
          associationName: "DayScheduleEmployee"
        attendanceDays:
          entityTypeName: "AttendanceDay"
          hasMany: true
          associationName: "AttendanceDayEmployee"

apiSchemaHelper.addType
      name: "AttendanceDay"
      apiVersion: 3
      dataProperties:
        uid: "uid"
        employee_id: "int"
        date: "string"
        shifts:
          complexType: "AttendanceShift"
          hasMany: true
      navigationProperties:
        employee:
          type: "Employee"
          assoc: "AttendanceDayEmployee"
          key: ["employee_id"]
```

So as you see, employee has many DaySchedule and AttendanceDay objects.

If I create three objects of this type in the following order:

```
  employee = createEntity "Employee", id: 20
  daySchedule = createEntity "DaySchedule", employee_id: 20
  attendanceDay = createEntity "AttendanceDay", employee_id: 20
```

Then all the navigationProperties are correctly made.
However if I put employee creation last:

```
  daySchedule = createEntity "DaySchedule", employee_id: 20
  attendanceDay = createEntity "AttendanceDay", employee_id: 20
  employee = createEntity "Employee", id: 20
```

Then employee.schedules is as expected, but employee.attendanceDays is an empty array.
